"""Generates the Heyu app icon from its spec (see README.md in this folder).

Writes:
  app/src/main/res/drawable/ic_launcher_foreground.xml   Android adaptive-icon foreground (also the themed icon)
  app/src/main/res/drawable/ic_launcher_background.xml   Android adaptive-icon background
  app/src/main/res/drawable/ic_notification.xml          status-bar icon: same artwork, cropped to fill the icon
  docs/logo/heyu-icon.svg                                full icon, square, orange background
  docs/logo/heyu-icon-foreground.svg                     white artwork on transparent

Run from anywhere:  python docs/logo/make_icon.py   (standard library only)
"""
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DRAWABLE = ROOT / "app/src/main/res/drawable"
DOCS = ROOT / "docs/logo"

# ---- Spec ----
CANVAS = 108            # adaptive-icon canvas, in dp; the launcher's 66dp safe circle is centered at (54,54)
ORANGE = "#FF7518"      # pumpkin orange background
WHITE = "#FFFFFF"       # artwork
W = 2.5                 # text-line thickness
SHIFT = -1.5            # top lines slid left (25% of the 6-unit gap to the bubble's left edge)

# Hourglass frame bars: 36 wide x 3 tall, fully rounded ends.
BAR1 = "M37.5,27h33a1.5,1.5 0,0 1,0 3h-33a1.5,1.5 0,0 1,0 -3z"   # x 36..72, y 27..30
BAR2 = "M37.5,78h33a1.5,1.5 0,0 1,0 3h-33a1.5,1.5 0,0 1,0 -3z"   # x 36..72, y 78..81
# Chat bubbles: 32x16 rounded rects (corner radius 6) with 10-wide triangular tails meeting at the neck (54,54).
TOP = "M44,32H64A6,6 0,0 1,70 38V42A6,6 0,0 1,64 48H59L54,54L49,48H44A6,6 0,0 1,38 42V38A6,6 0,0 1,44 32Z"
BOT = "M44,60H49L54,54L59,60H64A6,6 0,0 1,70 66V70A6,6 0,0 1,64 76H44A6,6 0,0 1,38 70V66A6,6 0,0 1,44 60Z"


# ---- Text lines ----
def quad(p0, c, p1, n=14):
    return [((1 - t) ** 2 * p0[0] + 2 * t * (1 - t) * c[0] + t ** 2 * p1[0],
             (1 - t) ** 2 * p0[1] + 2 * t * (1 - t) * c[1] + t ** 2 * p1[1]) for t in (i / n for i in range(n + 1))]


def line(p0, p1, n=6):
    return [(p0[0] + (p1[0] - p0[0]) * i / n, p0[1] + (p1[1] - p0[1]) * i / n) for i in range(n + 1)]


def dedupe(seq):
    out = []
    for p in seq:
        if not out or math.dist(out[-1], p) > 1e-6:
            out.append(p)
    return out


def hooked(y, turn_x):
    """Straight from x=44 to turn_x, then the shared hook: quadratic Bezier, control 5 right, end 3 right + 7.25 down."""
    return dedupe(line((44, y), (turn_x, y)) + quad((turn_x, y), (turn_x + 5, y), (turn_x + 3, y + 7.25)))


def band(pts):
    """Outline of a W-wide stroke along pts with square ends, as a closed path (a hole under evenOdd fill)."""
    def normal(i):
        a, b = pts[max(i - 1, 0)], pts[min(i + 1, len(pts) - 1)]
        dx, dy = b[0] - a[0], b[1] - a[1]
        d = math.hypot(dx, dy)
        return -dy / d, dx / d
    r = W / 2
    left = [(x + r * nx, y + r * ny) for (x, y), (nx, ny) in ((pts[i], normal(i)) for i in range(len(pts)))]
    right = [(x - r * nx, y - r * ny) for (x, y), (nx, ny) in ((pts[i], normal(i)) for i in range(len(pts)))]
    f = lambda p: f"{p[0]:.2f},{p[1]:.2f}"
    return ("M" + f(left[0]) + "".join("L" + f(p) for p in left[1:]) + "L" + f(right[-1])
            + "".join("L" + f(p) for p in reversed(right[:-1])) + "Z")


shift = lambda pts, dx: [(x + dx, y) for x, y in pts]
rot180 = lambda pts: [(CANVAS - x, CANVAS - y) for x, y in reversed(pts)]  # about the neck (54,54)

# Top bubble: lines run left to right, right ends hook down toward the neck.
top1 = shift(hooked(37.25, 57), SHIFT)
top2 = shift(hooked(41.75, 52), SHIFT)
# Bottom bubble: the same lines rotated 180 degrees, so left ends hook up out of the neck.
bot1, bot2 = rot180(top2), rot180(top1)

holes_top = [band(top1), band(top2)]
holes_bot = [band(bot1), band(bot2)]

# ---- Output ----
sep = "\n            "
(DRAWABLE / "ic_launcher_foreground.xml").write_text(f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Heyu icon: an hourglass whose top and bottom are chat bubbles, tails meeting at the neck.
     Text lines flow through it: in the top bubble their right ends hook down into the neck, in the bottom
     bubble their left ends hook up out of it (the top shapes rotated 180 degrees).
     Lines are holes (evenOdd) so the same drawing works as the one-color themed icon.
     108x108 adaptive-icon canvas; everything sits inside the 66dp safe circle.
     Generated by docs/logo/make_icon.py; spec in docs/logo/README.md. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:fillColor="{WHITE}" android:pathData="{BAR1}" />
    <path android:fillColor="{WHITE}" android:pathData="{BAR2}" />
    <path
        android:fillColor="{WHITE}"
        android:fillType="evenOdd"
        android:pathData="{TOP}{sep}{sep.join(holes_top)}" />
    <path
        android:fillColor="{WHITE}"
        android:fillType="evenOdd"
        android:pathData="{BOT}{sep}{sep.join(holes_bot)}" />
</vector>
''', encoding="utf-8")

(DRAWABLE / "ic_launcher_background.xml").write_text(f'''<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:fillColor="{ORANGE}" android:pathData="M0,0h108v108h-108z" />
</vector>
''', encoding="utf-8")


def svg(background):
    bg = f'  <rect width="{CANVAS}" height="{CANVAS}" fill="{background}"/>\n' if background else ""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1080" viewBox="0 0 {CANVAS} {CANVAS}">\n{bg}'
            f'  <path fill="{WHITE}" d="{BAR1}"/>\n  <path fill="{WHITE}" d="{BAR2}"/>\n'
            f'  <path fill="{WHITE}" fill-rule="evenodd" d="{TOP} {" ".join(holes_top)}"/>\n'
            f'  <path fill="{WHITE}" fill-rule="evenodd" d="{BOT} {" ".join(holes_bot)}"/>\n</svg>\n')


# Status-bar icon: Android draws only its shape (any color becomes white/grey), so the same white artwork
# works; cropped to a 56x56 square around it (bars span y 27..81) so it fills the tiny 24dp slot.
CROP = 56
off = (CANVAS - CROP) / 2
(DRAWABLE / "ic_notification.xml").write_text(f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Heyu status-bar icon. Generated by docs/logo/make_icon.py; spec in docs/logo/README.md. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="{CROP}"
    android:viewportHeight="{CROP}">
    <group android:translateX="-{off:g}" android:translateY="-{off:g}">
        <path android:fillColor="{WHITE}" android:pathData="{BAR1}" />
        <path android:fillColor="{WHITE}" android:pathData="{BAR2}" />
        <path
            android:fillColor="{WHITE}"
            android:fillType="evenOdd"
            android:pathData="{TOP}{sep}{sep.join(holes_top)}" />
        <path
            android:fillColor="{WHITE}"
            android:fillType="evenOdd"
            android:pathData="{BOT}{sep}{sep.join(holes_bot)}" />
    </group>
</vector>
''', encoding="utf-8")

(DOCS / "heyu-icon.svg").write_text(svg(ORANGE), encoding="utf-8")
(DOCS / "heyu-icon-foreground.svg").write_text(svg(None), encoding="utf-8")
print("wrote", ", ".join(p.name for p in [DRAWABLE / "ic_launcher_foreground.xml", DRAWABLE / "ic_launcher_background.xml",
                                          DRAWABLE / "ic_notification.xml",
                                          DOCS / "heyu-icon.svg", DOCS / "heyu-icon-foreground.svg"]))
